// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Friend struct {
	ID   string `json:"id"`
	User *User  `json:"user"`
}

type Mutation struct {
}

type Nutrition struct {
	ID       string `json:"id"`
	Meal     string `json:"meal"`
	Calories int    `json:"calories"`
	Date     string `json:"date"`
}

type Progress struct {
	ID           string  `json:"id"`
	Weight       float64 `json:"weight"`
	Measurements string  `json:"measurements"`
	Date         string  `json:"date"`
}

type Query struct {
}

type User struct {
	ID            string       `json:"id"`
	Email         string       `json:"email"`
	Profile       *UserProfile `json:"profile"`
	Workouts      []*Workout   `json:"workouts"`
	NutritionLogs []*Nutrition `json:"nutritionLogs"`
	Progress      []*Progress  `json:"progress"`
}

type UserProfile struct {
	Name            string   `json:"name"`
	FitnessGoals    []string `json:"fitnessGoals"`
	ActivityHistory []string `json:"activityHistory"`
}

type Workout struct {
	ID             string `json:"id"`
	Type           string `json:"type"`
	Duration       int    `json:"duration"`
	CaloriesBurned int    `json:"caloriesBurned"`
	Date           string `json:"date"`
}

type WorkoutPlan struct {
	ID          string   `json:"id"`
	Name        string   `json:"name"`
	Description string   `json:"description"`
	Goals       []string `json:"goals"`
}
